export * from "./Inicio"
export * from "./Blog"
export * from "./Gatos"
export * from "./Peces"
export * from "./Productos"
export * from "./Tortugas"
export * from "./Login"
export * from "./Registro"